### ISSUE TITLE
安装后没有显示按钮

### ISSUE THREAD

**Issue by 1844280369** [bzyzh/xkw-zujuan-script#1]
安装后，打开网页后并没有显示响应的按钮。

**Comment by nuym** [comment]
抱歉，现在才看到，这个问题前几天我也发现了，这周六更新修复。

**Comment by 1844280369** [comment]
> 抱歉，现在才看到，这个问题前几天我也发现了，这周六更新修复。

希望可以增加显示 题型：单选、多选题、计算题 等题型的显示 ；下载后带答案的每个题目会带2个答案，也希望 可以一起修复

**Comment by nuym** [comment]
> > 抱歉，现在才看到，这个问题前几天我也发现了，这周六更新修复。
> 
> 希望可以增加显示 题型：单选、多选题、计算题 等题型的显示 ；下载后带答案的每个题目会带2个答案，也希望 可以一起修复

开工中

**Comment by nuym** [comment]
> 安装后，打开网页后并没有显示响应的按钮。

有吧，我这边测试正常呢，你需要在类似于[测试页面](https://zujuan.xkw.com/11p2278894.html)打开脚本。

已修复答案无法分离的问题。

**Comment by nuym** [comment]
这边测试没问题了，你那边如果没问题请关闭issue qwp

**Comment by 1844280369** [comment]
11、在edge浏览器中依旧 不显示按钮 ，按照图中 所示注释 这几行就 可以正常显示。<img width="751" alt="1" src="https://github.com/user-attachments/assets/4efb8de3-9a38-4df2-99e2-7fd626621c39">
2、下载 带有答案版本的依旧会每个题目显示2次答案，如图 <img width="451" alt="2" src="https://github.com/user-attachments/assets/e68917e8-7bd3-4e2c-b51c-660786188db7">


以上描述是因为所使用的浏览器不一样造成的吗？

**Comment by 1844280369** [comment]
单独打印答案测试正常，“和试题一起打印”如之前所报结果。

建议优化：①增加显示 题型；②按键提示后的“取消 ”容易混淆，建议改为“仅打印试题”这种描述，当然用户也可以自己也能改。否则用户会认为是取消打印。

**Comment by 1844280369** [comment]
建议修改代码中 177-181行 ：
`        title: "是否需要打印答案?",
        showDenyButton: true,
        showCancelButton: true,
        confirmButtonText: "仅打印答案 ",
        denyButtonText:"试题+答案",
        cancelButtonText:"仅打印试题",`  
以让按钮提示更易理解。

**Comment by nuym** [comment]
> 建议修改代码中 177-181行 ： ` title: "是否需要打印答案?", showDenyButton: true, showCancelButton: true, confirmButtonText: "仅打印答案 ", denyButtonText:"试题+答案", cancelButtonText:"仅打印试题",` 以让按钮提示更易理解。

已完成，感谢您的贡献。
